### ISSUE TITLE
Building IRIS on Wakari

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/ipython-notebooks#1]
First we need to build Cartopy.

Cartopy depends on Shapely, which is included in Anacona (the scientific python distribution behind Wakari), but it also depends on the proj4 library, which is not on the system, so must be build proj4 locally, but make sure it's static because we can't have any local library dependencies if we want to successfully share environments.

**Comment by rsignell-usgs** [comment]
We now have conda-forge channel.    So we can close this.

**Comment by emiliom** [comment]
Heh. This whole repo is pretty old. Maybe it should be repurposed and reused for hosting notebooks, or deleted altogether and whatever useful content is left ported to another repo? Pinging @ocefpaf to see what he thinks.

**Comment by ocefpaf** [comment]
:+1: to close this repo. I can savage anything useful from here into https://github.com/ioos/notebooks_demos

**Comment by dpsnowden** [comment]
Agreed

**Comment by rsignell-usgs** [comment]
I don't see anything useful.   @ocefpaf, feel free to delete.
